//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SilvioBaldwinTsangaCadet_PP1_Projet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public string CodeAdmin { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string email { get; set; }
        public string MotDePasse { get; set; }
    }
}
