//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SilvioBaldwinTsangaCadet_PP1_Projet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guichet
    {
        public string CodeGuichet { get; set; }
        public Nullable<decimal> Solde { get; set; }
    }
}
