//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SilvioBaldwinTsangaCadet_PP1_Projet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int CodeTransaction { get; set; }
        public Nullable<int> CodeClient { get; set; }
        public string TypeTransaction { get; set; }
        public string De { get; set; }
        public string À { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<decimal> Montant { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Compte Compte { get; set; }
        public virtual Compte Compte1 { get; set; }
        public virtual TypesTransaction TypesTransaction { get; set; }
    }
}
